name: CI
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Run Java Hello World
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '8'

      - name: Compile Java
        run: javac HelloWorld.java

      - name: Run Java
        run: java HelloWorld

      
